require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cage. As you add validations to Cage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cage.create! valid_attributes
      get cages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cage = Cage.create! valid_attributes
      get cage_url(cage)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cage_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cage = Cage.create! valid_attributes
      get edit_cage_url(cage)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cage" do
        expect {
          post cages_url, params: { cage: valid_attributes }
        }.to change(Cage, :count).by(1)
      end

      it "redirects to the created cage" do
        post cages_url, params: { cage: valid_attributes }
        expect(response).to redirect_to(cage_url(Cage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cage" do
        expect {
          post cages_url, params: { cage: invalid_attributes }
        }.to change(Cage, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cages_url, params: { cage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cage" do
        cage = Cage.create! valid_attributes
        patch cage_url(cage), params: { cage: new_attributes }
        cage.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cage" do
        cage = Cage.create! valid_attributes
        patch cage_url(cage), params: { cage: new_attributes }
        cage.reload
        expect(response).to redirect_to(cage_url(cage))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cage = Cage.create! valid_attributes
        patch cage_url(cage), params: { cage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cage" do
      cage = Cage.create! valid_attributes
      expect {
        delete cage_url(cage)
      }.to change(Cage, :count).by(-1)
    end

    it "redirects to the cages list" do
      cage = Cage.create! valid_attributes
      delete cage_url(cage)
      expect(response).to redirect_to(cages_url)
    end
  end
end
